//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PC
{
	public virtual CPU CPU
	{
		get;
		set;
	}

	public virtual IEnumerable<GPU> GPU
	{
		get;
		set;
	}

	public virtual IEnumerable<RAM> RAM
	{
		get;
		set;
	}

}

